# Generated by Django 3.0.7 on 2020-06-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='is_ative',
            new_name='is_active',
        ),
    ]
