# Generated by Django 3.0.7 on 2020-06-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200621_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='quoted_status',
        ),
        migrations.AddField(
            model_name='status',
            name='quoted_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='api.Status'),
        ),
        migrations.RemoveField(
            model_name='status',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='status',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='api.Status'),
        ),
        migrations.RemoveField(
            model_name='status',
            name='retweeted_status',
        ),
        migrations.AddField(
            model_name='status',
            name='retweeted_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweets', to='api.Status'),
        ),
    ]
