# Generated by Django 3.0.7 on 2020-06-28 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200627_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='text',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
